Repository treyer/project-management-app, pull requests merged in 2022-05, with the labels that each got.

#3 Create api layer
  management-app/.env
  management-app/package-lock.json
  management-app/package.json
  management-app/src/App.tsx
  management-app/src/api/baseAPI.ts
  management-app/src/api/errors.ts
  management-app/src/api/types.ts
  management-app/src/api/usersAPI.ts
  management-app/src/constants.tsx
  management-app/src/logo.svg
Labels: feature

#6 feat: add basic app structure components and routes
  management-app/.editorconfig
  management-app/package-lock.json
  management-app/src/App.css
  management-app/src/App.tsx
  management-app/src/components/Footer/Footer.tsx
  management-app/src/components/Header/Header.css
  management-app/src/components/Header/Header.tsx
  management-app/src/constants.tsx
  management-app/src/index.tsx
  management-app/src/pages/AuthPage.tsx
  management-app/src/pages/BoardPage.tsx
  management-app/src/pages/MainPage.tsx
  management-app/src/pages/NotFoundPage.tsx
  management-app/src/pages/WelcomePage.tsx
  management-app/src/types.ts
Labels: feature

#5 feat: create API layer
  management-app/src/api/boardsAPI.ts
  management-app/src/api/columnsAPI.ts
  management-app/src/api/errors.ts
  management-app/src/api/fileAPI.ts
  management-app/src/api/tasksAPI.ts
  management-app/src/api/types.ts
  management-app/src/api/usersAPI.ts
Labels: feature

#9 feat: add main page
  management-app/.eslintrc.json
  management-app/package-lock.json
  management-app/public/assets/svg/board.svg
  management-app/src/App.tsx
  management-app/src/api/baseAPI.ts
  management-app/src/api/boardsAPI.ts
  management-app/src/api/columnsAPI.ts
  management-app/src/api/types.ts
  management-app/src/components/ConfirmMessage/ConfirmMessage.tsx
  management-app/src/components/Header/Header.tsx
  management-app/src/constants.ts
  management-app/src/pages/MainPage.tsx
  management-app/src/pages/MainPage/MainPage.tsx
  management-app/src/pages/MainPage/components/AddBoardBtn/AddBoardBtn.tsx
  management-app/src/pages/MainPage/components/Board/Board.tsx
  management-app/src/pages/MainPage/components/BoardModal/BoardModal.tsx
  management-app/src/pages/MainPage/slice/mainSlice.ts
  management-app/src/routes.tsx
  management-app/src/store.ts
Labels: feature, Improvement

#12 feat: implement Header and Footer markup with styles, responsive markup and modals
  management-app/.eslintrc.json
  management-app/package-lock.json
  management-app/public/assets/img/logo.png
  management-app/public/assets/img/logo_hover.png
  management-app/public/assets/svg/icon-search-black.svg
  management-app/public/assets/svg/icon-search-white.svg
  management-app/public/assets/svg/rss.svg
  management-app/public/favicon.ico
  management-app/src/App.css
  management-app/src/App.tsx
  management-app/src/components/BackLayer/BackLayer.tsx
  management-app/src/components/BurgerMenu/BurgerMenu.tsx
  management-app/src/components/Footer/Footer.module.css
  management-app/src/components/Footer/Footer.tsx
  management-app/src/components/GitLink/GitLink.tsx
  management-app/src/components/Header/Header.module.css
  management-app/src/components/Header/Header.tsx
  management-app/src/components/LanguageButton/LanguageButton.tsx
  management-app/src/components/LanguageSwitch/LanguageSwitch.tsx
  management-app/src/components/Logo/Logo.module.css
  management-app/src/components/Logo/Logo.tsx
  management-app/src/components/MenuModal/MenuModal.tsx
  management-app/src/components/NavButton/NavButton.tsx
  management-app/src/components/SearchBar/SearchBar.module.css
  management-app/src/components/SearchBar/SearchBar.tsx
  management-app/src/components/ThemeSwitch/ThemeSwitch.tsx
  management-app/src/components/UserMenu/UserMenu.tsx
  management-app/src/routes.tsx
  management-app/src/types.ts
Labels: feature

#13 feat: add dra-n-drop for taskCards
  management-app/package-lock.json
  management-app/package.json
  management-app/src/api/tasksAPI.ts
  management-app/src/api/types.ts
  management-app/src/index.tsx
  management-app/src/pages/BoardPage/BoardPage.tsx
  management-app/src/pages/BoardPage/boardSlice.ts
  management-app/src/pages/BoardPage/components/BoardColumn/BoardColumn.tsx
  management-app/src/pages/BoardPage/components/TaskCard/TaskCard.tsx
  management-app/src/pages/BoardPage/components/TaskCard/TaskCard.types.ts
Labels: feature

#16 feat: add NotFoundPage markup with styles, fix bug of Header and Footer images upload
  management-app/package-lock.json
  management-app/public/assets/img/page-not-found.png
  management-app/src/components/Footer/Footer.tsx
  management-app/src/components/Logo/Logo.tsx
  management-app/src/components/SearchBar/SearchBar.tsx
  management-app/src/pages/NotFoundPage.tsx
Labels: fix, feature

#15 feat: add welcome page
  management-app/public/assets/img/andrey.jpg
  management-app/public/assets/img/hero.png
  management-app/public/assets/img/lena.jpg
  management-app/public/assets/img/london5.png
  management-app/public/assets/img/marina.jpg
  management-app/src/App.tsx
  management-app/src/_redirects
  management-app/src/pages/WelcomePage.tsx
  management-app/src/pages/WelcomePage/WelcomePage.module.css
  management-app/src/pages/WelcomePage/WelcomePage.tsx
  management-app/src/pages/WelcomePage/components/TeamInfoCard.tsx
  management-app/src/pages/WelcomePage/constants.ts
  management-app/src/routes.tsx
Labels: feature

#18 Add internationalization to App
  management-app/.prettierignore
  management-app/package-lock.json
  management-app/package.json
  management-app/public/locales/en/translation.json
  management-app/public/locales/ru/translation.json
  management-app/src/auth/SignInForm/SignInForm.tsx
  management-app/src/auth/SignInForm/SignInForm.utils.ts
  management-app/src/auth/SignUpForm/SignUpForm.tsx
  management-app/src/auth/SignUpForm/SignUpForm.utils.ts
  management-app/src/components/ConfirmMessage/ConfirmMessage.tsx
  management-app/src/components/Footer/Footer.tsx
  management-app/src/components/Header/Header.tsx
  management-app/src/components/LanguageButton/LanguageButton.tsx
  management-app/src/components/LanguageSwitch/LanguageSwitch.tsx
  management-app/src/components/MenuModal/MenuModal.tsx
  management-app/src/components/SearchBar/SearchBar.module.css
  management-app/src/components/SearchBar/SearchBar.tsx
  management-app/src/index.tsx
  management-app/src/lang/english.ts
  management-app/src/lang/i18n.js
  management-app/src/lang/russian.ts
  management-app/src/pages/BoardPage/BoardPage.tsx
  management-app/src/pages/BoardPage/components/BoardColumn/BoardColumn.tsx
  management-app/src/pages/BoardPage/components/CreateColumnField/CreateColumnField.tsx
  management-app/src/pages/BoardPage/components/CreateTaskField/CreateTaskField.tsx
  management-app/src/pages/MainPage/MainPage.tsx
  management-app/src/pages/MainPage/components/AddBoardBtn/AddBoardBtn.tsx
  management-app/src/pages/MainPage/components/Board/Board.tsx
  management-app/src/pages/MainPage/components/BoardModal/BoardModal.tsx
  management-app/src/pages/WelcomePage/WelcomePage.tsx
  management-app/src/pages/WelcomePage/constants.ts
  management-app/src/routes.tsx
Labels: feature

#20 refactor: add CreateModal component
  management-app/public/assets/svg/board.svg
  management-app/public/locales/en/translation.json
  management-app/public/locales/ru/translation.json
  management-app/src/components/CreateModal/CreateModal.tsx
  management-app/src/components/Header/Header.tsx
  management-app/src/pages/BoardPage/BoardPage.tsx
  management-app/src/pages/BoardPage/components/CreateColumnModal/CreateColumnModal.module.scss
  management-app/src/pages/BoardPage/components/CreateColumnModal/CreateColumnModal.tsx
  management-app/src/pages/BoardPage/components/CreateColumnModal/CreateColumnModal.types.ts
  management-app/src/pages/BoardPage/components/CreateColumnModal/index.ts
  management-app/src/pages/MainPage/MainPage.tsx
  management-app/src/pages/MainPage/components/AddBoardBtn/AddBoardBtn.tsx
  management-app/src/pages/MainPage/components/Board/Board.tsx
  management-app/src/pages/MainPage/components/BoardModal/BoardModal.tsx
  management-app/src/pages/MainPage/slice/mainSlice.ts
  management-app/src/pages/WelcomePage/WelcomePage.module.css
Labels: Improvement

#25 refactor: edit board page
  management-app/public/locales/en/translation.json
  management-app/public/locales/ru/translation.json
  management-app/src/api/columnsAPI.ts
  management-app/src/api/tasksAPI.ts
  management-app/src/components/CreateModal/CreateModal.tsx
  management-app/src/index.tsx
  management-app/src/pages/BoardPage/BoardPage.tsx
  management-app/src/pages/BoardPage/boardSlice.ts
  management-app/src/pages/BoardPage/components/BoardColumn/BoardColumn.tsx
  management-app/src/pages/BoardPage/components/ColumnTitle/ColumnTitle.tsx
  management-app/src/pages/BoardPage/components/TaskCard/TaskCard.tsx
  management-app/src/pages/MainPage/MainPage.tsx
  management-app/src/pages/MainPage/components/Board/Board.tsx
  management-app/src/pages/WelcomePage/WelcomePage.tsx
Labels: feature, Improvement

#26 feat: implement theme switch
  management-app/package-lock.json
  management-app/public/assets/img/logo_dark_mode.png
  management-app/public/assets/img/logo_dark_mode_hover.png
  management-app/public/assets/img/office.png
  management-app/public/assets/svg/rss_dark_mode.svg
  management-app/public/locales/en/translation.json
  management-app/public/locales/ru/translation.json
  management-app/src/App.tsx
  management-app/src/auth/SignInForm/SignInForm.tsx
  management-app/src/auth/SignUpForm/SignUpForm.tsx
  management-app/src/components/Footer/Footer.module.css
  management-app/src/components/Footer/Footer.tsx
  management-app/src/components/GitLink/GitLink.tsx
  management-app/src/components/Header/Header.module.css
  management-app/src/components/Header/Header.tsx
  management-app/src/components/LanguageButton/LanguageButton.tsx
  management-app/src/components/Logo/Logo.tsx
  management-app/src/components/MenuModal/MenuModal.tsx
  management-app/src/components/NavButton/NavButton.tsx
  management-app/src/components/RssLogo/RssLogo.tsx
  management-app/src/components/SearchBar/SearchBar.module.css
  management-app/src/components/SearchBar/SearchBar.tsx
  management-app/src/components/ThemeSwitch/ThemeSwitch.tsx
  management-app/src/components/UserMenu/UserMenu.tsx
  management-app/src/lang/english.ts
  management-app/src/lang/russian.ts
  management-app/src/pages/WelcomePage/WelcomePage.tsx
  management-app/src/store.ts
  management-app/src/themes/theme.ts
  management-app/src/themes/themeSlice.ts
Labels: feature

#29 feat: add board title
  management-app/src/pages/BoardPage/BoardPage.tsx
  management-app/src/pages/BoardPage/components/BoardColumn/BoardColumn.tsx
  management-app/src/pages/BoardPage/components/CreateColumnField/CreateColumnField.tsx
  management-app/src/pages/BoardPage/components/CreateColumnField/CreateColumnField.types.ts
  management-app/src/pages/BoardPage/components/CreateColumnField/index.ts
  management-app/src/pages/BoardPage/components/CreateTaskField/CreateTaskField.tsx
  management-app/src/pages/BoardPage/components/CreateTaskField/CreateTaskField.types.ts
  management-app/src/pages/BoardPage/components/CreateTaskField/index.ts
  management-app/src/pages/BoardPage/components/TaskCard/TaskCard.tsx
  management-app/src/pages/WelcomePage/WelcomePage.tsx
  management-app/src/pages/WelcomePage/components/TeamInfoCard.tsx
Labels: Improvement

#31 refactor: set default value
  management-app/src/auth/SignInForm/SignInForm.tsx
  management-app/src/auth/SignUpForm/SignUpForm.tsx
  management-app/src/auth/authSlice.tsx
  management-app/src/pages/EditProfilePage/EditProfilePage.tsx
Labels: Improvement

#34 feat: add search
  management-app/public/locales/en/translation.json
  management-app/public/locales/ru/translation.json
  management-app/src/components/MenuModal/MenuModal.tsx
  management-app/src/components/SearchBar/SearchBar.tsx
  management-app/src/search/SearchModal/SearchModal.tsx
  management-app/src/search/SearchResultBoard/SearchResultBoard.tsx
  management-app/src/search/SearchResultColumn/SearchResultColumn.tsx
  management-app/src/search/SearchResultTask/SearchResultTask.tsx
  management-app/src/search/types.ts
  management-app/src/search/utils.ts
Labels: feature
